### ISSUE TITLE
Getting std error, while not using the std

### ISSUE THREAD

**Issue by UltiRequiem** [denoland/dnt#110]
Steps to reproduce:

```sh
git clone https://github.com/UltiRequiem/six.git && cd six && deno run -A scripts/node.ts
```

You will get:
```
[dnt] Building project...
[dnt] Top-level await cannot be used when distributing CommonJS (See deps/deno_land/std_0.119.0/log/mod.ts 211:1). Please re-organize your code to not use a top-level await or only distribute an ESM module by setting the 'cjs' build option to false.
error: Uncaught (in promise) Error: Build failed due to top-level await when creating CommonJS package.
        throw new Error(
              ^
    at build (https://deno.land/x/dnt@0.16.1/mod.ts:255:15)
    at async file:///home/ulti/disk/repos/six/scripts/node.ts:7:1
```

In my own code I'm not using top-level away, so reading the error, I understand that a dep is doing it.

I don't think this should affect the final user, any workaround?

https://github.com/UltiRequiem/six

**Comment by dsherret** [comment]
I should have a better error message for when it fails in the test code. I opened #111.

In this case, update the sleep dependency to `sleep@v1.2.1` and it should work.

**Comment by dsherret** [comment]
Also you will need to use the deno shim to make `Deno.test` work:

```
  shims: {
    deno: "dev",
  },
```
