### ISSUE TITLE
Add instructional error when someone doesn't have npm or node installed

### ISSUE THREAD

**Issue by dsherret** [denoland/dnt#16]
Currently it does this:

```
deno run -A --unstable dnt.ts
Check file:///workspaces/discordeno/dnt.ts
[dnt] Transforming...
[dnt] Running npm install...
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
  const process = Deno.run({
                       ^
    at Object.opSync (deno:core/01_core.js:142:12)
    at opRun (deno:runtime/js/40_process.js:27:17)
    at Object.run (deno:runtime/js/40_process.js:114:17)
    at runNpmCommand (https://deno.land/x/dnt@0.6.0/lib/utils.ts:32:24)
    at async build (https://deno.land/x/dnt@0.6.0/mod.ts:140:5)
    at async file:///workspaces/discordeno/dnt.ts:6:1
```

**Comment by dsherret** [comment]
Closed by #33.
