### ISSUE TITLE
Build error - "panicked at 'Text changes were overlapping"

### ISSUE THREAD

**Issue by bebraw** [denoland/dnt#201]
I tried to package gustwind using dnt but I ran into a serious error below:

```
[dnt] Transforming...
panicked at 'Text changes were overlapping. Past index was 37, but new change had index 36.', C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_ast-0.16.0\src\text_changes.rs:44:7

Stack:

Error
    at __wbg_new_693216e109162396 (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm.generated.js:331:19)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2947157)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2786454)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2887186)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2026653)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:1177794)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2632650)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2906146)
    at __wbg_adapter_22 (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm.generated.js:207:6)
    at real (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm.generated.js:191:14)


error: Uncaught (in promise) RuntimeError: unreachable
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2786512)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2887186)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2026653)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:1177794)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2632650)
    at <anonymous> (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm_bg.wasm:1:2906146)
    at __wbg_adapter_22 (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm.generated.js:207:6)
    at real (https://deno.land/x/dnt@0.29.1/lib/pkg/dnt_wasm.generated.js:191:14)
error: Failed at the build:gustwind-for-npm script
```

If you want to try debugging, you can find the code at https://github.com/gustwindjs/gustwind/tree/feat/gustwind-dnt . You'll need to have Velociraptor installed and after that you should run `vr build:gustwind-for-npm 0.1.0`.

Here's `deno --version` for reference:

```
deno 1.24.1 (release, x86_64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4
```

I'm using dnt version 0.29.1.

**Comment by dsherret** [comment]
I will try to take a look tomorrow. Probably something trivial.
