### ISSUE TITLE
Issues when using snapshot tests with DNT: tests and builds

### ISSUE THREAD

**Issue by orta** [denoland/dnt#254]
During type checking:

```
[dnt] Building project...
[dnt] Type checking...
src/deps/deno.land/std@0.168.0/testing/snapshot.ts:420:18 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

420       globalThis.addEventListener("unload", this.#teardown);
                     ~~~~~~~~~~~~~~~~

error: Uncaught Error: Had 1 diagnostics.
        throw new Error(`Had ${diagnostics.length} diagnostics.`);
              ^
    at build (https://deno.land/x/dnt@0.33.0/mod.ts:320:15)
    at async file:///home/orta/dev/puzmo/redwood-codegen-api-types/scripts/buildNPM.ts:7:1
```

During testing:

```

FAILURES

uses a rn to promise when we see an async tag
  Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/orta/dev/puzmo/redwood-codegen-api-types/npm/esm/tests/__snapshots__/preferPromiseFnWhenKnown.test.js.snap' imported from /home/orta/dev/puzmo/redwood-codegen-api-types/npm/esm/deps/deno.land/std@0.168.0/testing/snapshot.js
```

I bet for testing `.snap` files need to be migrated with other files? For build - unsure. Right now, I just made it skip both, though I may just drop the snapshot, it's only 1 and I only like using [inline snapshots](http://orta.io/notes/tests/inline-snapshots) anyway

**Comment by bcheidemann** [comment]
I got the tests running using the following hacks:

1. Rename the snapshot files to end in `.ts` so they can be transpiled during the build
2. Import the files in a generated `snapshots.ts` file and add this file as an entry point so the snapshot files will be transpiled
3. Edit `script/deps/deno.land/std@0.198.0/testing/snapshot.js` to remove the `file://` prefix and patch the path before the snapshot file is "required"

This still resulted in the snapshots failing tests due to `"` being replaced with `'`:

```
        [Diff] Actual / Expected
    
    
        {
          fields: Map(6) {
    -       'display' => {
    -         kind: 'option',
    +       "display" => {
    +         kind: "option",
              valueType: {
                fields: Map(8) {
    -             'firstperson_lefthand' => {
    -               kind: 'option',
    +             "firstperson_lefthand" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    +                   "rotation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    +                     kind: "array",
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    +                   "translation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    -                   }
    +                     kind: "array",
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'firstperson_righthand' => {
    -               kind: 'option',
    +             "firstperson_righthand" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    +                   "rotation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    +                     kind: "array",
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    +                   "translation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    -                   }
    +                     kind: "array",
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'fixed' => {
    -               kind: 'option',
    +             "fixed" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    -                     kind: 'option',
    +                   "rotation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    -                     kind: 'option',
    +                   "translation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    -                   }
    +                       kind: "array",
    +                     },
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'ground' => {
    -               kind: 'option',
    +             "ground" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    +                   "rotation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    +                     kind: "array",
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    -                     kind: 'option',
    +                   "translation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    -                   }
    +                       kind: "array",
    +                     },
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'gui' => {
    -               kind: 'option',
    +             "gui" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    -                     kind: 'option',
    +                   "rotation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    -                     kind: 'option',
    +                   "translation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    -                   }
    +                       kind: "array",
    +                     },
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'head' => {
    -               kind: 'option',
    +             "head" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    -                     kind: 'option',
    +                   "rotation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    +                   "translation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    -                   }
    +                     kind: "array",
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'thirdperson_lefthand' => {
    -               kind: 'option',
    +             "thirdperson_lefthand" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    +                   "rotation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    +                     kind: "array",
                        },
    -                   'scale' => {
    +                   "scale" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    +                     kind: "array",
                        },
    -                   'translation' => {
    +                   "translation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    -                   }
    +                     kind: "array",
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             'thirdperson_righthand' => {
    -               kind: 'option',
    +             "thirdperson_righthand" => {
    +               kind: "option",
                    valueType: {
                      fields: Map(3) {
    -                   'rotation' => {
    -                     kind: 'option',
    +                   "rotation" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'scale' => {
    -                     kind: 'option',
    +                   "scale" => {
    +                     kind: "option",
                          valueType: {
                            elementType: {
    -                         kind: 'primitive',
    -                         name: 'number'
    +                         kind: "primitive",
    +                         name: "number",
                            },
    -                       kind: 'array'
    -                     }
    +                       kind: "array",
    +                     },
                        },
    -                   'translation' => {
    +                   "translation" => {
                          elementType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    +                       kind: "primitive",
    +                       name: "number",
                          },
    -                     kind: 'array'
    -                   }
    +                     kind: "array",
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    -             }
    +                 kind: "struct",
    +               },
    +             },
                },
    -           kind: 'struct'
    -         }
    +           kind: "struct",
    +         },
            },
    -       'elements' => {
    -         kind: 'option',
    +       "elements" => {
    +         kind: "option",
              valueType: {
                elementType: {
                  fields: Map(3) {
    -               'faces' => {
    +               "faces" => {
                      fields: Map(6) {
    -                   'down' => {
    -                     kind: 'option',
    +                   "down" => {
    +                     kind: "option",
                          valueType: {
                            fields: Map(2) {
    -                         'texture' => {
    -                           kind: 'primitive',
    -                           name: 'string'
    +                         "texture" => {
    +                           kind: "primitive",
    +                           name: "string",
                              },
    -                         'uv' => {
    +                         "uv" => {
                                elementType: {
    -                             kind: 'primitive',
    -                             name: 'number'
    +                             kind: "primitive",
    +                             name: "number",
                                },
    -                           kind: 'array'
    -                         }
    +                           kind: "array",
    +                         },
                            },
    -                       kind: 'struct'
    -                     }
    +                       kind: "struct",
    +                     },
                        },
    -                   'east' => {
    +                   "east" => {
                          fields: Map(2) {
    -                       'texture' => {
    -                         kind: 'primitive',
    -                         name: 'string'
    +                       "texture" => {
    +                         kind: "primitive",
    +                         name: "string",
                            },
    -                       'uv' => {
    +                       "uv" => {
                              elementType: {
    -                           kind: 'primitive',
    -                           name: 'number'
    +                           kind: "primitive",
    +                           name: "number",
                              },
    -                         kind: 'array'
    -                       }
    +                         kind: "array",
    +                       },
                          },
    -                     kind: 'struct'
    +                     kind: "struct",
                        },
    -                   'north' => {
    +                   "north" => {
                          fields: Map(2) {
    -                       'texture' => {
    -                         kind: 'primitive',
    -                         name: 'string'
    +                       "texture" => {
    +                         kind: "primitive",
    +                         name: "string",
                            },
    -                       'uv' => {
    +                       "uv" => {
                              elementType: {
    -                           kind: 'primitive',
    -                           name: 'number'
    +                           kind: "primitive",
    +                           name: "number",
                              },
    -                         kind: 'array'
    -                       }
    +                         kind: "array",
    +                       },
                          },
    -                     kind: 'struct'
    +                     kind: "struct",
                        },
    -                   'south' => {
    +                   "south" => {
                          fields: Map(2) {
    -                       'texture' => {
    -                         kind: 'primitive',
    -                         name: 'string'
    +                       "texture" => {
    +                         kind: "primitive",
    +                         name: "string",
                            },
    -                       'uv' => {
    +                       "uv" => {
                              elementType: {
    -                           kind: 'primitive',
    -                           name: 'number'
    +                           kind: "primitive",
    +                           name: "number",
                              },
    -                         kind: 'array'
    -                       }
    +                         kind: "array",
    +                       },
                          },
    -                     kind: 'struct'
    +                     kind: "struct",
                        },
    -                   'up' => {
    +                   "up" => {
                          fields: Map(2) {
    -                       'texture' => {
    -                         kind: 'primitive',
    -                         name: 'string'
    +                       "texture" => {
    +                         kind: "primitive",
    +                         name: "string",
                            },
    -                       'uv' => {
    +                       "uv" => {
                              elementType: {
    -                           kind: 'primitive',
    -                           name: 'number'
    +                           kind: "primitive",
    +                           name: "number",
                              },
    -                         kind: 'array'
    -                       }
    +                         kind: "array",
    +                       },
                          },
    -                     kind: 'struct'
    +                     kind: "struct",
                        },
    -                   'west' => {
    +                   "west" => {
                          fields: Map(2) {
    -                       'texture' => {
    -                         kind: 'primitive',
    -                         name: 'string'
    +                       "texture" => {
    +                         kind: "primitive",
    +                         name: "string",
                            },
    -                       'uv' => {
    +                       "uv" => {
                              elementType: {
    -                           kind: 'primitive',
    -                           name: 'number'
    +                           kind: "primitive",
    +                           name: "number",
                              },
    -                         kind: 'array'
    -                       }
    +                         kind: "array",
    +                       },
                          },
    -                     kind: 'struct'
    -                   }
    +                     kind: "struct",
    +                   },
                      },
    -                 kind: 'struct'
    +                 kind: "struct",
                    },
    -               'from' => {
    +               "from" => {
                      elementType: {
    -                   kind: 'primitive',
    -                   name: 'number'
    +                   kind: "primitive",
    +                   name: "number",
                      },
    -                 kind: 'array'
    +                 kind: "array",
                    },
    -               'to' => {
    +               "to" => {
                      elementType: {
    -                   kind: 'primitive',
    -                   name: 'number'
    +                   kind: "primitive",
    +                   name: "number",
                      },
    -                 kind: 'array'
    -               }
    +                 kind: "array",
    +               },
                  },
    -             kind: 'struct'
    +             kind: "struct",
                },
    -           kind: 'array'
    -         }
    +           kind: "array",
    +         },
            },
    -       'gui_light' => {
    -         kind: 'option',
    +       "gui_light" => {
    +         kind: "option",
              valueType: {
    -           kind: 'primitive',
    -           name: 'string'
    -         }
    +           kind: "primitive",
    +           name: "string",
    +         },
            },
    -       'overrides' => {
    -         kind: 'option',
    +       "overrides" => {
    +         kind: "option",
              valueType: {
                elementType: {
                  fields: Map(2) {
    -               'model' => {
    -                 kind: 'primitive',
    -                 name: 'string'
    +               "model" => {
    +                 kind: "primitive",
    +                 name: "string",
                    },
    -               'predicate' => {
    +               "predicate" => {
                      fields: Map(15) {
    -                   'angle' => {
    -                     kind: 'option',
    +                   "angle" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'blocking' => {
    -                     kind: 'option',
    +                   "blocking" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'broken' => {
    -                     kind: 'option',
    +                   "broken" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'brushing' => {
    -                     kind: 'option',
    +                   "brushing" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'cast' => {
    -                     kind: 'option',
    +                   "cast" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'charged' => {
    -                     kind: 'option',
    +                   "charged" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'filled' => {
    -                     kind: 'option',
    +                   "filled" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'firework' => {
    -                     kind: 'option',
    +                   "firework" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'level' => {
    -                     kind: 'option',
    +                   "level" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'pull' => {
    -                     kind: 'option',
    +                   "pull" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'pulling' => {
    -                     kind: 'option',
    +                   "pulling" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'throwing' => {
    -                     kind: 'option',
    +                   "throwing" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'time' => {
    -                     kind: 'option',
    +                   "time" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'tooting' => {
    -                     kind: 'option',
    +                   "tooting" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
                        },
    -                   'trim_type' => {
    -                     kind: 'option',
    +                   "trim_type" => {
    +                     kind: "option",
                          valueType: {
    -                       kind: 'primitive',
    -                       name: 'number'
    -                     }
    -                   }
    +                       kind: "primitive",
    +                       name: "number",
    +                     },
    +                   },
                      },
    -                 kind: 'struct'
    -               }
    +                 kind: "struct",
    +               },
                  },
    -             kind: 'struct'
    +             kind: "struct",
                },
    -           kind: 'array'
    -         }
    +           kind: "array",
    +         },
            },
    -       'parent' => {
    -         kind: 'option',
    +       "parent" => {
    +         kind: "option",
              valueType: {
    -           kind: 'primitive',
    -           name: 'string'
    -         }
    +           kind: "primitive",
    +           name: "string",
    +         },
            },
    -       'textures' => {
    -         kind: 'option',
    +       "textures" => {
    +         kind: "option",
              valueType: {
                fields: Map(5) {
    -             'layer0' => {
    -               kind: 'option',
    +             "layer0" => {
    +               kind: "option",
                    valueType: {
    -                 kind: 'primitive',
    -                 name: 'string'
    -               }
    +                 kind: "primitive",
    +                 name: "string",
    +               },
                  },
    -             'layer1' => {
    -               kind: 'option',
    +             "layer1" => {
    +               kind: "option",
                    valueType: {
    -                 kind: 'primitive',
    -                 name: 'string'
    -               }
    +                 kind: "primitive",
    +                 name: "string",
    +               },
                  },
    -             'layer2' => {
    -               kind: 'option',
    +             "layer2" => {
    +               kind: "option",
                    valueType: {
    -                 kind: 'primitive',
    -                 name: 'string'
    -               }
    +                 kind: "primitive",
    +                 name: "string",
    +               },
                  },
    -             'particle' => {
    -               kind: 'option',
    +             "particle" => {
    +               kind: "option",
                    valueType: {
    -                 kind: 'primitive',
    -                 name: 'string'
    -               }
    +                 kind: "primitive",
    +                 name: "string",
    +               },
                  },
    -             'spyglass' => {
    -               kind: 'option',
    +             "spyglass" => {
    +               kind: "option",
                    valueType: {
    -                 kind: 'primitive',
    -                 name: 'string'
    -               }
    -             }
    +                 kind: "primitive",
    +                 name: "string",
    +               },
    +             },
                },
    -           kind: 'struct'
    -         }
    -       }
    +           kind: "struct",
    +         },
    +       },
          },
    -     kind: 'struct'
    +     kind: "struct",
        }
    
        at assertSnapshot (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/snapshot.js:481:15)
        at async run (/home/ben/repos/gentype/npm/script/test.js:123:9)
        at async Object.<anonymous> (/home/ben/repos/gentype/npm/script/test.js:132:9)
        at async TestSuiteInternal.runTest (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/_test_suite.js:307:13)
        at async TestSuiteInternal.runTest (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/_test_suite.js:292:17)
        at async Object.fn (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/_test_suite.js:265:25)
        at async Object.step (/home/ben/repos/gentype/npm/test_runner.js:136:21)
        at async TestSuiteInternal.run (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/_test_suite.js:273:13)
        at async Object.fn (/home/ben/repos/gentype/npm/script/deps/deno.land/std@0.198.0/testing/_test_suite.js:130:29)
        at async runTestDefinitions (/home/ben/repos/gentype/npm/test_runner.js:54:13)
  fail
```

Is anyone currently working on this? If not, I may have capacity to look into it.

**Comment by joscha** [comment]
@orta For the 1st issue have a look here: https://github.com/denoland/deno_std/pull/4957#issuecomment-2147598172

For snapshots I tried copying them into the target folder via:
```ts
await copy("src/v1/tests/__snapshots__", "npm/esm/v1/tests/__snapshots__", { overwrite: true });
```

however the import is tried with `.js.snap` instead of `.ts.snap` and they don't seem to be picked up in the transformation phase.

**Comment by stefnotch** [comment]
I thought I'd be smart and decided to copy over the snapshot files. 

I also set `await build({ scriptModule: false, ... })`, since the world is moving to [ESM-only](https://antfu.me/posts/move-on-to-esm-only)

```ts
async postBuild() {

for await (const snapshot of expandGlob("*/__snapshots__/*.snap")) {
  const resultPath = path.join(
    outDir,
    "esm",
    path.relative(".", snapshot.path).replace(
      /\.ts\.snap$/,
      ".js.snap",
    ),
  );

  await ensureDir(
    path.dirname(resultPath),
  );
  await Deno.copyFile(snapshot.path, resultPath);
}

}
```

But then it fails while executing the tests!
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".snap" for E:\git\webgpu\wesl-js\mini-parse\dist\esm\test\__snapshots__\Collect.test.js.snap
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:183:9)
      at defaultGetFormat (node:internal/modules/esm/get_format:209:36)
      at defaultLoad (node:internal/modules/esm/load:119:22)
      at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:519:32)
error: Uncaught (in promise) Error: npm run test failed with exit code 1
      throw new Error(
            ^
    at runCommand (https://jsr.io/@deno/dnt/0.41.3/lib/utils.ts:56:13)
    at eventLoopTick (ext:core/01_core.js:178:7)
    at async build (https://jsr.io/@deno/dnt/0.41.3/mod.ts:419:5)
    at async file:///E:/git/webgpu/wesl-js/mini-parse/scripts/build_npm.ts:10:1
```

The reason for that seems to be that the snapshot library is using an `import` statement. And of course that fails when the extension is `.snap`.
https://github.com/denoland/std/blob/61f9fd399c7e58751fa6e2d44af6f213b964371d/testing/snapshot.ts#L401

**Comment by bcheidemann** [comment]
> The reason for that seems to be that the snapshot library is using an `import` statement. And of course that fails when the extension is `.snap`. https://github.com/denoland/std/blob/61f9fd399c7e58751fa6e2d44af6f213b964371d/testing/snapshot.ts#L401

FWIW, you can specify a different path in your tests like this:

```ts
assertSnapshot(ctx, expected, { path: './__snapshots__/test.snap.js' });

// or

const assertSnapshot = createAssertSnapshot({ path: './__snapshots__/test.snap.js' });

assertSnapshot(ctx, expected);
```

**Comment by stefnotch** [comment]
Inline snapshots tests are now supported in Deno!
Since they live right in the source code, they do not suffer from the missing snapshot files :)

https://jsr.io/@std/testing/doc/unstable-snapshot/~/assertInlineSnapshot
