### ISSUE TITLE
`Property 'main' does not exist on type 'ImportMeta'.` on `import.meta.main`

### ISSUE THREAD

**Issue by scarf005** [denoland/dnt#255]
### Log
```ts
 deno run -A scripts/build_npm.ts 0.1.0
[dnt] Transforming...
[dnt] Running npm install...

added 11 packages, and audited 12 packages in 10s

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking...
src/mod.ts:52:17 - error TS2339: Property 'main' does not exist on type 'ImportMeta'.

52 if (import.meta.main) {
                   ~~~~

error: Uncaught Error: Had 1 diagnostics.
        throw new Error(`Had ${diagnostics.length} diagnostics.`);
              ^
    at build (https://deno.land/x/dnt@0.33.1/mod.ts:320:15)
    at async file:///home/scarf/repo/ifexpr/scripts/build_npm.ts:6:1
```

### System version
```sh
 deno --version
deno 1.30.0 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by Gaubee** [comment]
I have already create the PR for this fix #322.

You can now use my DNT as a temporary replacement
```
import { build, emptyDir } from "https://deno.land/x/gaubee_dnt/mod.ts";
```
