### ISSUE TITLE
esm.sh import with pinned version results in an error

### ISSUE THREAD

**Issue by alexgleason** [denoland/dnt#275]
https://esm.sh/#docs Ctrl+F "Pinning Build Version"

It's preferred to pin the esm.sh _build version_ (in addition to the npm package version) so deno.lock doesn't get out of sync. With a pinned esm.sh URL such as this:

```ts
export { type Filter, matchFilter, nip13 } from 'https://esm.sh/v114/nostr-tools@1.8.4';
```

we get the following error:

```
Task npm deno run -A scripts/npm.ts
[dnt] Transforming...
[dnt] Running npm install...
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "v114/nostr-tools" of package "v114/nostr-tools@1.8.4": name can only contain URL-friendly characters.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2023-04-17T01_00_58_188Z-debug-0.log
error: Uncaught (in promise) Error: npm install failed with exit code 1
        throw new Error(
              ^
    at runCommand (https://deno.land/x/dnt@0.34.0/lib/utils.ts:57:15)
    at async build (https://deno.land/x/dnt@0.34.0/mod.ts:210:5)
    at async file:///home/alex/Projects/strfry-policies/scripts/npm.ts:5:1
```

Removing the pin works perfectly, so this is a problem with the way esm.sh URLs are handled:

```ts
export { type Filter, matchFilter, nip13 } from 'https://esm.sh/nostr-tools@1.8.4'; // this works (notice no v114)
```

**Comment by alexgleason** [comment]
Using `?pin=114` at the end of the URL (instead of as a path in the URL) works as a workaround.

**Comment by dsherret** [comment]
@hansSchall would you be able to open a new issue? It's easy for stuff to get lost in old closed issues and the fix here might be unrelated.
