### ISSUE TITLE
error TS9005 on dependency type checking

### ISSUE THREAD

**Issue by bdarcus** [denoland/dnt#280]
I hope I'm not missing something obvious, but with this repo:

https://github.com/bdarcus/csln-deno-test

Running `deno check` or `deno task cli` results in no errors or warnings.

But when I do `deno run -A scripts/build_npm.ts 0.1.0`, I get this TS9005 error:

```typescript
[dnt] Transforming...
[dnt] Running npm install...

added 11 packages, and audited 12 packages in 839ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking...
src/deps/esm.sh/v119/class-transformer@0.5.1/deno/class-transformer.js:2:1 - error TS9005: Declaration emit for this file requires using private name 'e'. An explicit type annotation may unblock declaration emit.

2 import * as dntShim from "../../../../../_dnt.shims.js";
  ~~~~~~

error: Uncaught (in promise) Error: Had 1 diagnostics.
        throw new Error(`Had ${diagnostics.length} diagnostics.`);
              ^
    at build (https://deno.land/x/dnt@0.34.0/mod.ts:323:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///home/bruce/Code/csln-deno-test/scripts/build_npm.ts:6:1
```

**Comment by bdarcus** [comment]
Hmm ... changing the import statements to use the `npm` prefix removed the error.
