### ISSUE TITLE
dnt doesn't handle node:async_hooks (regardless of mapping)

### ISSUE THREAD

**Issue by uriva** [denoland/dnt#358]
dnt can't handle 

```
panicked at 'unexpected exception: JsValue(TypeError: Unsupported scheme "node:" for module "node:async_hooks". Supported schemes: ["data:","blob:","file:","http:","https:"].
TypeError: Unsupported scheme "node:" for module "node:async_hooks". Supported schemes: ["data:","blob:","file:","http:","https:"].
    at getValidatedScheme (https://deno.land/x/deno_cache@0.4.1/file_fetcher.ts:56:11)
    at FileFetcher.fetch (https://deno.land/x/deno_cache@0.4.1/file_fetcher.ts:234:20)
    at FetchCacher.load (https://deno.land/x/deno_cache@0.4.1/cache.ts:127:30)
    at fetch_specifier (https://deno.land/x/dnt@0.33.1/lib/pkg/snippets/dnt-wasm-a15ef721fa5290c5/helpers.js:6:22)
    at __wbg_fetchspecifier_a6bda29173284144 (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm.generated.js:277:21)
    at <anonymous> (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm_bg.wasm:1:1821055)
    at <anonymous> (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm_bg.wasm:1:1569984)
    at <anonymous> (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm_bg.wasm:1:2478438)
    at <anonymous> (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm_bg.wasm:1:1096665)
    at <anonymous> (https://deno.land/x/dnt@0.33.1/lib/pkg/dnt_wasm_bg.wasm:1:2371355))', wasm\src\lib.rs:23:1
```

(this import works both in node and deno)

code:
```ts
import { AsyncLocalStorage } from "node:async_hooks";
```

reproduction:

```
git clone github.com/uriva/gamlajs
cd gamla
deno task build
```

**Comment by uriva** [comment]
oops this works in 39
