### ISSUE TITLE
Need webSocket shim just to use WebSocket types

### ISSUE THREAD

**Issue by alexgleason** [denoland/dnt#372]
I am emitting just an ESM package. In browsers, `WebSocket` is a globally available interface. In my types, I use `WebSocket` as a type only (no runtime code), but this fails with dnt, unless I specify `webSocket: true` in my shims.

Since I'm only using WebSocket as a type, I don't want the shim to be added to the output.

```
➜  NSpec git:(main) ✗ deno task npm 0.1.0
Task npm deno run -A scripts/npm.ts "0.1.0"
[dnt] Transforming...
[dnt] Running npm install...

added 19 packages, and audited 20 packages in 644ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Emitting ESM package...
npm/src/interfaces/NProfilePointer.ts:6:12 - error TS4033: Property 'relays' of exported interface has or is using private name 'WebSocket'.

6   relays?: WebSocket['url'][];
             ~~~~~~~~~
npm/src/interfaces/NStore.ts:22:12 - error TS4033: Property 'relays' of exported interface has or is using private name 'WebSocket'.

22   relays?: WebSocket['url'][];
              ~~~~~~~~~
npm/src/interfaces/NostrSigner.ts:10:32 - error TS4057: Return type of method from exported interface has or is using private name 'WebSocket'.

10   getRelays?(): Promise<Record<WebSocket['url'], { read: boolean; write: boolean }>>;
                                  ~~~~~~~~~

error: Uncaught (in promise) Error: Had 3 emit diagnostics.
      throw new Error(`Had ${emitResult.diagnostics.length} emit diagnostics.`);
            ^
    at emit (https://deno.land/x/dnt@0.40.0/mod.ts:435:13)
    at build (https://deno.land/x/dnt@0.40.0/mod.ts:361:5)
    at eventLoopTick (ext:core/01_core.js:63:7)
    at async file:///home/alex/Projects/NSpec/scripts/npm.ts:5:1
```

**Comment by alexgleason** [comment]
I actually just want to use Deno's WebSocket definition. :thinking:

**Comment by alexgleason** [comment]
Btw, `package` is a required field. I can't specify just `typesPackage`:

```
[dnt] Transforming...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')
  value = value.trim();
```

Been messing with it trying to make it work, eg by setting `package` also to `@types/ws`:

```js
    custom: [{
      package: {
        name: '@types/ws',
        version: '^8.5.4',
        peerDependency: false,
      },
      typesPackage: {
        name: '@types/ws',
        version: '^8.5.4',
        peerDependency: false,
      },
      globalNames: [{
        name: 'WebSocket',
        exportName: 'default',
        typeOnly: true,
      }],
    }],
```

That results in this:

```
➜  NSpec git:(main) ✗ deno task npm 0.1.0
Task npm deno run -A scripts/npm.ts "0.1.0"
[dnt] Transforming...
[dnt] Running npm install...

added 25 packages, and audited 26 packages in 786ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking ESM...
src/_dnt.shims.ts:1:43 - error TS6137: Cannot import type declaration files. Consider importing 'ws' instead of '@types/ws'.

1 export { type default as WebSocket } from "@types/ws";
                                            ~~~~~~~~~~~
src/_dnt.test_shims.ts:3:43 - error TS6137: Cannot import type declaration files. Consider importing 'ws' instead of '@types/ws'.

3 export { type default as WebSocket } from "@types/ws";
                                            ~~~~~~~~~~~

error: Uncaught (in promise) Error: Had 2 diagnostics.
          throw new Error(`Had ${diagnostics.length} diagnostics.`);
                ^
    at getProgramAndMaybeTypeCheck (https://deno.land/x/dnt@0.40.0/mod.ts:457:17)
    at build (https://deno.land/x/dnt@0.40.0/mod.ts:345:17)
    at eventLoopTick (ext:core/01_core.js:63:7)
    at async file:///home/alex/Projects/NSpec/scripts/npm.ts:5:1
```

**Comment by alexgleason** [comment]
It turns out all I needed to do was add `DOM` to `compilerOptions`:

```ts
  compilerOptions: {
    lib: ['ES2021', 'DOM'],
  },
```
