### ISSUE TITLE
NPM reports invalid package name when importing esm.sh/@preact/signals

### ISSUE THREAD

**Issue by hansSchall** [denoland/dnt#392]
similar error message to #275 

```bash
deno task npm
Task npm deno run -A scripts/build_npm.ts
[dnt] Transforming...
[dnt] Running npm install...
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "stable/preact" of package "stable/preact@10.19.2": name can only contain URL-friendly characters.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hansi\AppData\Local\npm-cache\_logs\2024-03-26T13_28_08_851Z-debug-0.log
error: Uncaught (in promise) Error: npm install failed with exit code 1
      throw new Error(
            ^
    at runCommand (https://jsr.io/@deno/dnt/0.41.0/lib/utils.ts:56:13)        
    at eventLoopTick (ext:core/01_core.js:169:7)
    at async build (https://jsr.io/@deno/dnt/0.41.0/mod.ts:250:5)
    at async file:///D:/dev/rpc-broker/scripts/build_npm.ts:5:1
```

This is my deps.ts:

```ts
export { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";
export * from "https://esm.sh/@preact/signals@1.2.2/";
export { effect } from "https://esm.sh/@preact/signals@1.2.2/";
export * from "https://esm.sh/preact@10.20.1";
export { Packr, Unpackr } from "https://deno.land/x/msgpackr@v1.10.1/index.js";
export { concat } from "https://deno.land/std@0.184.0/bytes/concat.ts";
```

When I change the import to `https://esm.sh/preact?pin=10.20.1`, I get another error:

```
error: Uncaught (in promise) "Specifier https://esm.sh/stable/preact@10.19.2/denonext/hooks.js with version 10.19.2 did not match specifier https://esm.sh/stable/preact@10.20.1/denonext/preact.mjs with version 10.20.1."
```

Changing the import to `@10.19.2` or `@10.19.1` doesn't change anything.

Without specifying any version, the error reports a conflict between `hooks.js@10.19.2` and `preact.mjs@10.19.5`

I found out that the problematic import ist `@preact/signals`, it includes preact as devDependency.

Importing `preact` and `@preact/signals` via `npm:` works.

I am using `jsr:@deno/dnt@^0.41.0`

**Comment by hansSchall** [comment]
It works, if I change the imports like this:

```ts
export * from "npm:@preact/signals";
export { effect } from "npm:@preact/signals";
export * from "https://esm.sh/preact@10.20.1/hooks";
```

This doesn't work:

```ts
export * from "npm:@preact/signals";
export { effect } from "npm:@preact/signals";
export * from "npm:preact/hooks";
```
