### ISSUE TITLE
`Promise.withResolvers` causes type check error

### ISSUE THREAD

**Issue by uriva** [denoland/dnt#440]
I'm seeing this:

```
[dnt] Type checking ESM...
src/_dnt.test_polyfills.ts:1:9 - error TS2669: Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.

1 declare global {
          ~~~~~~
src/_dnt.test_polyfills.ts:13:13 - error TS2339: Property 'withResolvers' does not exist on type 'PromiseConstructor'.

13 if (Promise.withResolvers === undefined) {
               ~~~~~~~~~~~~~
src/_dnt.test_polyfills.ts:14:11 - error TS2339: Property 'withResolvers' does not exist on type 'PromiseConstructor'.

14   Promise.withResolvers = () => {
             ~~~~~~~~~~~~~
src/src/taskBouncer.test.ts:38:8 - error TS2339: Property 'withResolvers' does not exist on type 'PromiseConstructor'.

38       .withResolvers<void>();
          ~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Had 4 diagnostics.
          throw new Error(`Had ${diagnostics.length} diagnostics.`);
                ^
    at getProgramAndMaybeTypeCheck (https://jsr.io/@deno/dnt/0.41.3/mod.ts:468:17)
    at build (https://jsr.io/@deno/dnt/0.41.3/mod.ts:354:17)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async file:///home/uri/uriva/abstract-bot-api/build_npm.ts:8:1
```

**Comment by uriva** [comment]
meanwhile poly-filling it myself worked

```
// https://github.com/denoland/dnt/issues/440
const promiseWithResolver = () => {
  const obj = {};
  // @ts-expect-error no typing
  obj.promise = new Promise<void>((resolve) => {
    // @ts-expect-error no typing
    obj.resolve = resolve;
  });
  return obj as { promise: Promise<void>; resolve: () => void };
};
```
